### ISSUE TITLE
how to use the tool

### ISSUE THREAD

**Issue by hackereye** [bigship/TrafficSpy#1]
I run this tool，but Without success.
Please explain the meaning of the parameters.

**Comment by bigship** [comment]
Sorry pal, I didn't notice the issue for more than .. a year ? What a shame ..
Anyway, in order to run the script, you need python 2.7.x and [pylibpcap](http://sourceforge.net/projects/pylibpcap/) library installed, and it only support Linux 32-bit platform.

how to use:
First, make sure you are in root privilege, then in a terminal type `python trafficspy.py eth0`, and you are ready to go. (eth0 is the network interface you want to monitor. You can change to eth1/eth2/wlan0 etc depending on your own situation)

You can also set a traffic filter after the network interface name, say you only want to sniff TCP traffic, and you could do that as: `python trafficspy.py eth0 tcp`
